name: Build and Deploy Full Stack App

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Vue frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Make Maven Wrapper executable
        run: chmod +x ./backend/mvnw

      - name: Build Spring Boot backend
        working-directory: ./backend
        run: ./mvnw clean package -DskipTests

      # 1️⃣ Stop and clean old app
      - name: Stop old app on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cmd /c "echo Killing process on port 8090... >> C:\root\hama\deploy.log"
            cmd /c "for /f \"tokens=5\" %a in ('netstat -ano ^| find \":8090\" ^| find \"LISTENING\"') do taskkill /PID %a /F"
            cmd /c "del /Q C:\root\hama\backend\target\*.jar"

      # 2️⃣ Copy new JAR
      - name: Deploy JAR to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./backend/target/*.jar"
          target: "C:/root/hama"

      # 3️⃣ Start new version in background
      - name: Start new app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cmd /c "cd C:\root\hama && for %f in (*.jar) do start \"\" cmd /c \"java -jar %f --server.port=8090 >> C:\root\hama\app.log 2>&1\""
